# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boufetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='aula',
            field=models.CharField(max_length=20),
        ),
    ]
