# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boufetapp', '0002_auto_20160919_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.IntegerField()),
                ('aula', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_del_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nombre_del_producto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='coca_colaCantidad',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='horario_de_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='laysCantidad',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='milanesaCantidad',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='tartinCantidad',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
