# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boufetapp', '0003_auto_20160920_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='horario_de_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
