# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boufetapp', '0004_auto_20160920_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='aula_de_entrega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boufetapp.Aula'),
            preserve_default=False,
        ),
    ]
