# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boufetapp', '0005_pedido_aula_de_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_del_pedido',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
